### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by AryanChothani** [talyssonoc/node-api-boilerplate#69]
@nfroidure 
 i am getting this type of error when i try to call create todo api 

i am adding todo and todoitems in this boilerplate

error is as below

"(node:7788) UnhandledPromiseRejectionWarning: TypeError: Object.defineProperty called on non-object
    at defineProperty (<anonymous>)
    at new decorator (H:\node_boilerplate\node_modules\structure\src\attributes\decorator.js:45:5)
    at CreateTodo.execute (H:\node_boilerplate\src\app\todo\CreateTodo.js:13:18)
    at create (H:\node_boilerplate\src\interfaces\http\todo\TodosController.js:33:16)
    at Layer.handle [as handle_request] (H:\node_boilerplate\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\node_boilerplate\node_modules\express\lib\router\route.js:137:13)
    at injectMiddleware (H:\node_boilerplate\node_modules\awilix-express\lib\inject.js:11:12)
    at Layer.handle [as handle_request] (H:\node_boilerplate\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\node_boilerplate\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\node_boilerplate\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (H:\node_boilerplate\node_modules\express\lib\router\layer.js:95:5)
    at H:\node_boilerplate\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (H:\node_boilerplate\node_modules\express\lib\router\index.js:335:12)
    at next (H:\node_boilerplate\node_modules\express\lib\router\index.js:275:10)
    at injectMiddleware (H:\node_boilerplate\node_modules\awilix-express\lib\inject.js:11:12)
    at Layer.handle [as handle_request] (H:\node_boilerplate\node_modules\express\lib\router\layer.js:95:5)
(node:7788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

this is my [repository](https://github.com/AryanChothani/node_boilerplate) with all changes i have done

**Comment by talyssonoc** [comment]
The problem is here, this is not Structure is meant to be used https://github.com/AryanChothani/node_boilerplate/blob/master/src/domain/todo/Todo.js#L3-L10, you're supposed to use a class with it, check this https://structure.js.org/schema-concept/shorthand-and-complete-attribute-definition
